baseurl = "https://duongquoctue.com/"
languageCode = "en-us"
theme = "hugo_theme_pickles"
enableGitInfo = true
# Copyright notice. This is displayer in the footer.
copyright = "&copy; From Rinzler with 🔥"

### Config for the theme
Title = "Duong Quoc Tue"
# Short subtitle/tagline. This is displayed in the header.
subtitle = "Keeping myself inspired and motivated."

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"
#Disqus
disqusShortname = "duongquoctue"
disqus_url = "https://duongquoctue.com"

[params]
logo = "/static/images/ava.jpg"
favicon = "/static/icons/favicon.ico"
hideWordCount = true
hideReadingTime = true
paginate = 6
custom_css = ["/css/custom.css"]
# Social accounts. Link to these accounts are displayed in the header and
# footer
facebook = "rnzlrdqt"
github = "duongquoctue"
linkedin = "duongquoctue"
twitter = "duongquoctue"

author = "Tue Duong"
authorwebsite = "https://duongquoctue.com/"
avatar = "/images/avatar.jpg"
bio = "Software Engineer @ OpenCommerce Group"
contact = "mailto:duongquoctue@icloud.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false

# Will lower case keywords in both queries and in the indexes.
toLower = true

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "author"
toLower = true
weight = 30
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10